{
 "title": "Deployments status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Successful Deployments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_deployment_metadata_generation[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Deployments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_deployment_status_replicas_unavailable[${__range}]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Deployments",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (deployment) (max_over_time(kube_deployment_status_replicas_unavailable[$__range])) > 0",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Deployment HistoryState",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_condition{condition=\"Available\", status=\"true\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "DORA Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (deployment) (changes(kube_deployment_metadata_generation[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}