{
 "title": "Grafana Stack",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_namespace", "label": "Namespace", "query": "monitoring" },
   { "name": "grafana_namespace", "query": "monitoring" },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$grafana_namespace\", container=\"grafana\"}[$__rate_interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$grafana_namespace\", container=\"grafana\"}[$__rate_interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$grafana_namespace\", pod=~\"grafana-.*-.*\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$grafana_namespace\", pod=~\"grafana-.*-.*\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod=~\"grafana-.*-.*\", namespace=\"$grafana_namespace\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"$grafana_namespace\", pod=~\"grafana-.*-.*\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$grafana_namespace\", pod=~\"grafana-.*-.*\", resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$grafana_namespace\", pod=~\"grafana-.*-.*\", resource=\"memory\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$grafana_namespace\", pod=~\"grafana-.*-.*\"}[$__rate_interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$grafana_namespace\", pod=~\"grafana-.*-.*\"}[$__rate_interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"$grafana_namespace\", pod=~\"grafana-.*-.*\"}[1m]))",
     "legendFormat": "Restarts"
    }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$prometheus_namespace\", container=\"prometheus\"}[1m]))",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$prometheus_namespace\", container=\"prometheus\"}[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$prometheus_namespace\", pod=~\"prometheus-prometheus-kube-prometheus-prometheus-0\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$prometheus_namespace\", pod=~\"prometheus-prometheus-kube-prometheus-prometheus-0\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod=~\"prometheus-prometheus-kube-prometheus-prometheus-.*\", namespace=\"$prometheus_namespace\", container=\"prometheus\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"$prometheus_namespace\", pod=~\"prometheus-prometheus-kube-prometheus-prometheus-.*\", container=\"prometheus\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$prometheus_namespace\", pod=~\"prometheus-prometheus-kube-prometheus-prometheus-0\", resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$prometheus_namespace\", pod=~\"prometheus-prometheus-kube-prometheus-prometheus-0\", resource=\"memory\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$prometheus_namespace\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\"}[$__rate_interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$prometheus_namespace\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\"}[$__rate_interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"$prometheus_namespace\", pod=\"prometheus-prometheus-kube-prometheus-prometheus-0\"}[1m]))",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Number of Metrics",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series)",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Relabels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(scrape_samples_post_metric_relabeling[5m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks)",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Post Metric Relabeling",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(scrape_samples_post_metric_relabeling[5m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Head Time Range",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_head_max_time) - min(prometheus_tsdb_head_min_time)",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Compactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total[15m])",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Rule Evaluation Failures",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total[5m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Chunks In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_chunks_created_total[5m]))",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_head_chunks_removed_total[5m]))",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "Sum" }
   ]
  },
  {
   "title": "Targets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "targets": [
    { "expr": "sum by(namespace)(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scrape Failures",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(job)(rate(scrape_samples_scraped{job!=\"prometheus\"}[5m]) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Success by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "(sum by(namespace)(up)) / count by(namespace)(up)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration by Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(scrape_duration_seconds) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples Scraped by Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series Added",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(scrape_series_added) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds) by (slice)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Sample Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_samples_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}